version: "3"
services:
  robot1:
    image: roschain:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robot1
    environment:
      - ROBOT_NAME=robot1
      - ROBOT_TYPE=robot
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - SECRET=lkfpoewrvcmlsdjfjehf
      - UPDATE_INTERVAL=5
    volumes:
      - ./robot1:/robot_ws/src/multirobot_sim/files
  robot2:
    image: roschain:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robot2
    environment:
      - ROBOT_NAME=robot2
      - ROBOT_TYPE=robot
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - SECRET=lkfpoewrvcmlsdjfjehf
      - UPDATE_INTERVAL=5
    volumes:
      - ./robot2:/robot_ws/src/multirobot_sim/files